version: '3'

services:
  db:
    image: postgres:alpine
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: presence
    volumes: 
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
